---
- hosts: nodes
  remote_user: "{{ slice }}"
  tasks:
     - name: install pip
       apt: name=python-pip update_cache=yes

     - name: install beanstalkc
       pip: name=beanstalkc

     - name: install pyyaml
       pip: name=pyyaml
