---
- hosts: localhost
  connection: local
  vars:
  tasks:

  - name: Create directory for slice files
    file: path={{ slicedir }}
      state=directory

  - name: Create SSH key for slice
    shell: ssh-keygen -t rsa -f {{ keyfile }} -P ""
      creates={{ keyfile }}

- hosts: nodes
  sudo: yes
  gather_facts: no
  remote_user: "{{ dockeruser }}"
  tasks:

  - name: Create a slice
    docker: name={{ slice }}
      hostname={{ slice }}.{{ inventory_hostname }}
      image={{ docker_image | default("geeproject/phusion-baseimage:0.3") }}
      publish_all_ports=yes
      restart_policy=always
    ignore_errors: yes
    register: result

  - name: Create user account for the slice
    user: name={{ slice }}
      shell=/usr/local/sbin/dosh
    when: result|success

  - name: Create user's .ssh directory
    file: path=/home/{{ slice }}/.ssh
      state=directory
      owner={{ slice }}
      mode=0700
    when: result|success

  - name: Inject ssh key into container
    copy: src={{ keyfile }}.pub
      dest=/mnt/docker/{{ dockerfs }}/mnt/{{ docker_containers[0]['Id'] }}/{{ rootfs }}/root/.ssh/authorized_keys
    when: result|success

  - name: SSH key for user account
    copy: src={{ keyfile }}.pub
      dest=/home/{{ slice }}/.ssh/authorized_keys
      owner={{ slice }}
      mode=0600
    when: result|success

- hosts: localhost
  tasks:
  - name: Create helper files
    template: src=templates/{{ item.name }}
      dest={{ slicedir }}/{{ item.name }}
    with_items:
    - name: ssh-config
    - name: ansible-hosts
    - name: ansible.cfg
    - name: fabfile.py
    - name: README.txt

  - name: Create tarball
    shell: cd {{ slicedir }}; tar czf {{ tarball }} *
    when: tarball != ""
