---
- hosts: localhost
  connection: local
  vars:
  tasks:

  - name: Create directory for slice files
    file: path={{ slicedir }}
      state=directory

  - name: Create SSH key for slice
    shell: ssh-keygen -t rsa -f {{ keyfile }} -P ""
      creates={{ keyfile }}

- hosts: nodes
  sudo: no
#  remote_user: ubuntu
  remote_user: gee
  tasks:

  - name: Create a slice
    docker: name={{ slice }}
      hostname={{ slice }}.{{ inventory_hostname }}
      image={{ docker_image | default("geeproject/phusion-baseimage:0.1") }}
      expose=22 
      publish_all_ports=yes

  - name: Inject ssh key
    sudo: yes
    copy: src={{ keyfile }}.pub
      dest=/var/lib/docker/aufs/mnt/{{ docker_containers[0]['Id'] }}/root/.ssh/authorized_keys

#  - debug: var=docker_containers

  - name: Set up /etc/hosts in container
    sudo: yes
    template: src=templates/etc-hosts
      dest=/var/lib/docker/aufs/mnt/{{ docker_containers[0]['Id'] }}/etc/workaround-docker-2267/hosts

- hosts: localhost
  tasks:
  - name: Create helper files
    template: src=templates/{{ item.name }}
      dest={{ slicedir }}/{{ item.name }}
    with_items:
    - name: ssh-config
    - name: ansible-hosts
    - name: fabfile.py

  - name: Create tarball
    shell: cd {{ slicedir }}; tar czf {{ tarball }} *
    when: tarball != ""
