---
- hosts: nodes
  remote_user: "{{ dockeruser }}"
  gather_facts: no
  sudo: yes
  tasks:

  - name: Delete a slice
    docker: name={{ slice }}
      image={{ docker_image | default("phusion/baseimage:0.9.15") }}
      state=absent
    ignore_errors: yes

  - name: Remove user account
    user: name={{ slice }} state=absent

- hosts: localhost
  connection: local
  tasks:
  - name: Remove slice directory
    file: path={{ slicedir }}
      state=absent
